/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RBD_H_RPCGEN
#define _RBD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct ContactEntry {
	char *name;
	char *phone;
	char *address;
	char *email;
};
typedef struct ContactEntry ContactEntry;

struct SearchResult {
	bool_t found;
	ContactEntry *entry;
};
typedef struct SearchResult SearchResult;

#define RBDPROG 0x30090949
#define RDBVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INSERT 1
extern  int * insert_1(ContactEntry *, CLIENT *);
extern  int * insert_1_svc(ContactEntry *, struct svc_req *);
#define REMOVE 2
extern  int * remove_1(char **, CLIENT *);
extern  int * remove_1_svc(char **, struct svc_req *);
#define SEARCH 3
extern  SearchResult * search_1(char **, CLIENT *);
extern  SearchResult * search_1_svc(char **, struct svc_req *);
extern int rbdprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INSERT 1
extern  int * insert_1();
extern  int * insert_1_svc();
#define REMOVE 2
extern  int * remove_1();
extern  int * remove_1_svc();
#define SEARCH 3
extern  SearchResult * search_1();
extern  SearchResult * search_1_svc();
extern int rbdprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ContactEntry (XDR *, ContactEntry*);
extern  bool_t xdr_SearchResult (XDR *, SearchResult*);

#else /* K&R C */
extern bool_t xdr_ContactEntry ();
extern bool_t xdr_SearchResult ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RBD_H_RPCGEN */
