/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rbd.h"

bool_t
xdr_ContactEntry (XDR *xdrs, ContactEntry *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 32))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->phone, 32))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->address, 64))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->email, 32))
		 return FALSE;
	return TRUE;
}
